on: 
  push:
  workflow_dispatch:
jobs:
  wget_zip:
    runs-on: ubuntu-latest
    name: Test the GZip Functionality
    steps:
      - name: Download and extract
        uses: SzymonDukla/action-curl-gunzip@master
        id: hello
        with:
          url: "https://download.db-ip.com/free/dbip-city-lite-2022-11.mmdb.gz"
          destination: "db.mmdb"
      - name : Test that the desired folder is present
        run : "ls -la $GITHUB_WORKSPACE/db.mmdb"
      - name : Test that the zip file is not present
        run : "if [[ -f db.mmdb.gz ]]; then exit 1; else exit 0; fi"